<a class="cbe-colab-launch" href="https://colab.research.google.com/github/tlliuca/AI4ChemEng/blob/main/dsmles/assignments/hw01-numpy.ipynb" target="_blank" rel="noopener noreferrer" title="Open this notebook in Google Colab (opens in a new tab)">
<img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" width="146" height="25">
</a>

In [ ]:
# Run this cell first in a fresh notebook environment.
%pip install -q "numpy<2.4" pandas matplotlib scikit-learn pycse shap xgboost umap-learn jupyterquiz==2.9.6.2 uncertainties

In [ ]:
# Included CBE 4427 data; no original-course server is contacted.
from pathlib import Path
import base64, json, tempfile, zlib
_course_embedded = json.loads(zlib.decompress(base64.b64decode('eNrtVE2ukzEMvMpT11Vefhwn4Qpc4ZOqCiroop/Qa4EF4u7MjJ8QB2DZ3cgZexxn4l+H8/1+/bLfLvvj/vq43L5d3s6P72+X0+fz45w+3X8cPrwcHtfb5XS77sd/CR+3PR9bz2mtbS9CY257BWqpIdaAPBXfdlPM27Z3IEt9bLsDrZSRMYBmqohNZXTb9qXTWlGZIkOlSwkmzgtkPKeMkoU6PS0SLAoUwC7uRNXiqsAuh7IaqVNBZ62lLJatEPOSOlDReYdArYLG8xY3Qa1quoqjxdrVAZup1EIBXLqO4KKZOjUeitUlWBFtELMpiUa1GlODmg3VbVAzTIvQFG1Mg5rVVMl1EQSh1lYqaL1NQTbZlrgFaZYFHQSDmpWUMRujWlaaNaVx+ga1NlLm00GtTb2YeUhgejZUzNC6TRVraNKW0thvDzU+YA81Qw+9CvLGPe420WTn3fBqqNu7rskL9bjbYNoQYaCHTjXYhoSlURskPCsqWxVFOV+vGjXu4y2CpIZFiMIhRB5ORVEfMl5hdOqc8/AlBxTAkUVwSA1IOYaA2Y0aUaQNaHlLmTAsMkjoMpYI/te6I9TEnYKGkY+ltAk4w/wTFWaYv/GbhBpnN8P8nMd8/2Xk9viE6He6CFCY4ceMyczwY6VCTJETXzFF/r74zmAuvlhPA82uJmhkmt6GT7p6PD/aWvFiGQ0svljTwNeUE3jdtWS25fzVWb7iT81FvuJPzTU8KNzEMGELS/Pj5q4qnEnJLp0lzoi4Sr6bkr87L2FavJRQ1drgNqGHmct1gjpaDNwntBjrlLhoV7yHTQldcHI9cadgLGpZSwXDVPkYLOiH48uB2/T1689cTs8d+9yxzx373LHPHftfd+zvPxR1lgg=')))
_course_cache = Path(tempfile.mkdtemp(prefix="cbe4427-"))
def course_file(name):
    """Use a local course file, or the copy embedded in this notebook."""
    for root in [Path.cwd(), *Path.cwd().parents]:
        for candidate in [root / "dsmles" / name, root / name]:
            if candidate.is_file():
                return str(candidate)
    if name not in _course_embedded:
        raise FileNotFoundError("Course resource not included: " + name)
    target = (_course_cache / name).resolve()
    if _course_cache not in target.parents:
        raise ValueError("Invalid course resource path")
    target.parent.mkdir(parents=True, exist_ok=True)
    if not target.exists():
        target.write_text(_course_embedded[name])
    return str(target)


```{note}
Practice resource for CBE 4427. Your instructor specifies assigned activities, deadlines, submission requirements, and assessment criteria. Example points or rubrics below are part of the practice material.
```

# Homework 1: NumPy Fundamentals

Complete all exercises below. Show your work and include comments explaining your approach.

In [2]:
import numpy as np
import matplotlib.pyplot as plt

## Problem 1: Array Creation and Basic Operations

You have reactor temperature data collected every minute for 2 hours.

In [3]:
# Load temperature data (K) - collected every minute for 2 hours
import shutil

url = course_file('data/hw01_temperature_data.csv')
shutil.copyfile(url, "temperature_data.csv")

data = np.loadtxt("temperature_data.csv", delimiter=",", skiprows=1)
time_min = data[:, 0]
temperatures = data[:, 1]

print(f"Loaded {len(temperatures)} temperature measurements")
print(f"Time range: {time_min[0]} to {time_min[-1]} minutes")

Loaded 120 temperature measurements
Time range: 0.0 to 119.0 minutes


**1a.** Calculate the mean, standard deviation, minimum, and maximum temperature using NumPy functions.

In [4]:
# Your code here


**1b.** Use boolean indexing to find all time points (indices) where temperature exceeded 355 K. How many such points are there?

In [5]:
# Your code here


**1c.** Calculate the rate of temperature change (dT/dt) using `np.diff()`. What is the maximum heating rate? What is the maximum cooling rate?

In [6]:
# Your code here


## Problem 2: Vectorized Calculations

The Arrhenius equation describes reaction rate constants:

$$k = A \exp\left(-\frac{E_a}{RT}\right)$$

where:
- A = 1.0 × 10⁸ s⁻¹ (pre-exponential factor)
- Ea = 50,000 J/mol (activation energy)
- R = 8.314 J/(mol·K) (gas constant)
- T = temperature in Kelvin

**2a.** Create an array of temperatures from 300 K to 500 K in 20 K increments using `np.arange()`.

In [7]:
# Your code here


**2b.** Calculate the rate constant k at each temperature using vectorized operations (no loops!).

In [8]:
# Your code here
A = 1.0e8  # s^-1
Ea = 50000  # J/mol
R = 8.314  # J/(mol·K)


**2c.** Plot k vs T. Use a logarithmic y-axis (`plt.semilogy()`) since k varies over several orders of magnitude.

In [9]:
# Your code here


**2d.** By what factor does the rate constant increase when going from 350 K to 400 K?

In [10]:
# Your code here


## Problem 3: 2D Arrays and Broadcasting

You have experimental data from a batch reactor stored in a 2D array where:
- Rows represent different experiments
- Columns are: Temperature (K), Pressure (atm), Conversion (%)

In [11]:
# Experimental data: each row is [Temperature, Pressure, Conversion]
np.random.seed(42)
data = np.array([
    [350, 1.0, 45],
    [350, 2.0, 52],
    [350, 3.0, 58],
    [400, 1.0, 62],
    [400, 2.0, 71],
    [400, 3.0, 78],
    [450, 1.0, 75],
    [450, 2.0, 83],
    [450, 3.0, 89]
])

print("Data shape:", data.shape)
print(data)

Data shape: (9, 3)
[[350.   1.  45.]
 [350.   2.  52.]
 [350.   3.  58.]
 [400.   1.  62.]
 [400.   2.  71.]
 [400.   3.  78.]
 [450.   1.  75.]
 [450.   2.  83.]
 [450.   3.  89.]]


**3a.** Extract the Temperature column (column 0) and the Conversion column (column 2) into separate arrays.

In [12]:
# Your code here


**3b.** Find all experiments where conversion exceeded 70%. Return the full rows for these experiments.

In [13]:
# Your code here


**3c.** Calculate the mean conversion for each temperature level (350, 400, 450 K). 

*Hint: Use boolean indexing to select rows for each temperature, then calculate mean of the conversion column.*

In [14]:
# Your code here
